### ISSUE TITLE
Works over IndexedDB in Safari?

### ISSUE THREAD

**Issue by nolanlawson** [jensarps/IDBWrapper#68]
Looking through the closed issues (like https://github.com/jensarps/IDBWrapper/pull/65), am I correct in assuming that this doesn't work with Apple's version of IndexedDB? Asking because there are still environments like WKWebView where not only is IndexedDB broken (due to [Apple's bugs](https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26)), but [WebSQL is disabled too](https://bugs.webkit.org/show_bug.cgi?id=137760), so you can't shim it.

**Comment by jensarps** [comment]
Hm, I'd say it depends™. 

IDBWrapper is not affected by some of the bugs due to it's "one-store-per-database" policy (e.g. the PK issue). So, if you play it safe, no arrays for keys and no `multiEntry` indexes, you should be fine – but, If you offer a framework and do not know what end-users will do with it, and can't filter their input, then I'd consider it unsafe.

That said, I sometimes get weird results when [running the tests](http://jensarps.de/tests/IDBWrapper/test/) in different Safaris, and I got a little weary of understanding and fighting Safari weirdnesses (tests running 1.4.1, I'm a little behind there). 

I fear one would need to do some extensive testing using an extended test suite with multiple Safari versions and create a result table to be able to fully answer the question :/

**Comment by jensarps** [comment]
I get solid results for the tests for 1.6.1 in Safari now. Also, shim can now be set as preferred engine.

So, Safari itself is supported; issues with creating alternate storage means for UIWebView or WKWebView are outside of the scope of IDBWrapper.

I'll close this now; however, feel free to get back to me on this if you want to.
