### ISSUE TITLE
Doesn't work in Safari (Private Window) and in iframe on iOS

### ISSUE THREAD

**Issue by tomilenko** [jensarps/IDBWrapper#76]
Hello,

I have the issue with IDBWrapper functionality in Safari  (Private Window) and in the iframe on iOS.
Error message: "TypeError: null is not an object (evaluating 'a')".
In another browsers and devices, everything works well.

I have used 1.6.0 version. In the latest version (1.7.1) I have the same issue.

How can I solve this issue? Do you have any suggestions?
Please check the simple code example below:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/idbwrapper/1.6.0/idbstore.min.js"></script>
    <script src="script.js"></script>
</head>
<body>
    <h1>Test</h1>
</body>
</html>
```

```
var customers = new IDBStore({
  dbVersion: 1,
  storeName: 'customer',
  keyPath: 'id',
  autoIncrement: true,
  onStoreReady: function(){
    console.log('Store ready!');
  }
});

```

You can check it on this page: https://gist.github.com/jensarps/1391434#file-index-html 

Thanks!

**Comment by jensarps** [comment]
Thanks for reporting!

Safari sadly is very complicated in regards to IndexedDB. That it disallows IndexedDB in private mode is unfortunate, but understandable (it wouldn't be allowed to persist data in private mode). The iframe on iOS issue might be due to how Apple implements that iframe – I have no idea about the Safari internals.

So, sadly, I do not see a way to solve the issues, or work around them; Safari is just preventing access to IndexedDB – and there is nothing one can do about it.

**Comment by BigBlueHat** [comment]
Apparently, Firefox also has this bug (since 5 years ago):
https://bugzilla.mozilla.org/show_bug.cgi?id=781982

```
OpenError: A mutation operation was attempted on a database that did not allow mutations.
InvalidStateError
```

I'm guessing this is a "wait on the browsers" scenario, but thought I'd share the information I'd found while trying to understand this failure.

Thanks for this project!
🎩

**Comment by jensarps** [comment]
Thanks for sharing!

Yeah, I wish the spec had a section on how to deny access to IndexedDB in case you're in private/incognito mode – then we'd have less weird bugs and we'd know why things fail.
